language: c
compiler:
  - gcc
script:
  - autoreconf -i
  - ./configure
  - make
after_success:
  - make check || exit 1
before_install:
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo sh -c "echo 'deb https://labs.consol.de/repo/testing/ubuntu precise main' >> /etc/apt/sources.list"
  - gpg --keyserver keys.gnupg.net --recv-keys F8C1CA08A57B9ED7
  - gpg --armor --export F8C1CA08A57B9ED7 | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install autoconf
  - sudo apt-get install build-essential
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install naemon-dev
notifications:
  irc:
    channels:
      - "chat.freenode.net#naemon-devel"
    on_success: change
    on_failure: always
    skip_join: true
